{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: pyTelegramBotAPI in /var/mobile/Containers/Data/Application/23FFC571-30C3-46B6-A0F6-ABAF425905DE/Library/lib/python3.13/site-packages (4.35.0)\n",
      "Requirement already satisfied: aiohttp in /var/mobile/Containers/Data/Application/23FFC571-30C3-46B6-A0F6-ABAF425905DE/Library/lib/python3.13/site-packages (from pyTelegramBotAPI) (3.14.1)\n",
      "Requirement already satisfied: requests in /private/var/containers/Bundle/Application/629ACC25-898A-4D73-B691-7A9935A6A4A8/Carnets.app/Library/lib/python3.13/site-packages (from pyTelegramBotAPI) (2.32.5)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /var/mobile/Containers/Data/Application/23FFC571-30C3-46B6-A0F6-ABAF425905DE/Library/lib/python3.13/site-packages (from aiohttp->pyTelegramBotAPI) (2.7.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in /var/mobile/Containers/Data/Application/23FFC571-30C3-46B6-A0F6-ABAF425905DE/Library/lib/python3.13/site-packages (from aiohttp->pyTelegramBotAPI) (1.4.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /private/var/containers/Bundle/Application/629ACC25-898A-4D73-B691-7A9935A6A4A8/Carnets.app/Library/lib/python3.13/site-packages (from aiohttp->pyTelegramBotAPI) (25.3.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /var/mobile/Containers/Data/Application/23FFC571-30C3-46B6-A0F6-ABAF425905DE/Library/lib/python3.13/site-packages (from aiohttp->pyTelegramBotAPI) (1.8.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /var/mobile/Containers/Data/Application/23FFC571-30C3-46B6-A0F6-ABAF425905DE/Library/lib/python3.13/site-packages (from aiohttp->pyTelegramBotAPI) (6.7.1)\n",
      "Requirement already satisfied: propcache>=0.2.0 in /var/mobile/Containers/Data/Application/23FFC571-30C3-46B6-A0F6-ABAF425905DE/Library/lib/python3.13/site-packages (from aiohttp->pyTelegramBotAPI) (0.5.2)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in /var/mobile/Containers/Data/Application/23FFC571-30C3-46B6-A0F6-ABAF425905DE/Library/lib/python3.13/site-packages (from aiohttp->pyTelegramBotAPI) (1.24.2)\n",
      "Requirement already satisfied: idna>=2.0 in /private/var/containers/Bundle/Application/629ACC25-898A-4D73-B691-7A9935A6A4A8/Carnets.app/Library/lib/python3.13/site-packages (from yarl<2.0,>=1.17.0->aiohttp->pyTelegramBotAPI) (3.10)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /private/var/containers/Bundle/Application/629ACC25-898A-4D73-B691-7A9935A6A4A8/Carnets.app/Library/lib/python3.13/site-packages (from requests->pyTelegramBotAPI) (3.4.3)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /private/var/containers/Bundle/Application/629ACC25-898A-4D73-B691-7A9935A6A4A8/Carnets.app/Library/lib/python3.13/site-packages (from requests->pyTelegramBotAPI) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /private/var/containers/Bundle/Application/629ACC25-898A-4D73-B691-7A9935A6A4A8/Carnets.app/Library/lib/python3.13/site-packages (from requests->pyTelegramBotAPI) (2025.8.3)\n",
      "\r"
     ]
    }
   ],
   "source": [
    "!pip install pyTelegramBotAPI\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: pip in /private/var/containers/Bundle/Application/629ACC25-898A-4D73-B691-7A9935A6A4A8/Carnets.app/Library/lib/python3.13/site-packages (25.2)\n",
      "Collecting pip\n",
      "  Downloading pip-26.1.2-py3-none-any.whl.metadata (4.6 kB)\n",
      "Downloading pip-26.1.2-py3-none-any.whl (1.8 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.8/1.8 MB\u001b[0m \u001b[31m667.9 kB/s\u001b[0m  \u001b[33m0:00:03\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "Installing collected packages: pip\n",
      "Successfully installed pip-26.1.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install --upgrade pip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import telebot\n",
    "from telebot.types import ReplyKeyboardMarkup, KeyboardButton, WebAppInfo, InlineKeyboardMarkup, InlineKeyboardButton\n",
    "\n",
    "# Твой токен от @BotFather\n",
    "TOKEN = '8609236930:AAHExw0HXJMBMTNSUPL1F5DXaqLZBmsiRS8'\n",
    "\n",
    "# ВСТАВЬ СЮДА СВОЙ ЦИФРОВОЙ ID, КОТОРЫЙ УЗНАЛ В @userinfobot\n",
    "ADMIN_ID = 5265210907 \n",
    "\n",
    "bot = telebot.TeleBot(TOKEN)\n",
    "\n",
    "# Ссылка на твою карту на GitHub Pages\n",
    "WEB_APP_URL = 'https://akkauntbravl549-afk.github.io/WaterMap/'\n",
    "\n",
    "# Временная база данных в памяти бота для хранения шагов предложки\n",
    "# Структура: {user_id: {'coords': '...', 'photo': '...'}}\n",
    "pending_submissions = {}\n",
    "\n",
    "@bot.message_handler(commands=['start'])\n",
    "def start_message(message):\n",
    "    markup = ReplyKeyboardMarkup(resize_keyboard=True)\n",
    "    web_app = WebAppInfo(url=WEB_APP_URL)\n",
    "    btn = KeyboardButton(text=\"💧 Открыть карту воды\", web_app=web_app)\n",
    "    markup.add(btn)\n",
    "    \n",
    "    welcome_text = (\n",
    "        \"Привет! Я бот для поиска бесплатной питьевой воды.\\n\\n\"\n",
    "        \"Нажми на кнопку ниже, чтобы открыть интерактивную карту.\\n\\n\"\n",
    "        \"✨ Нашел новый кулер, которого нет на карте? Напиши команду /add, чтобы предложить его!\"\n",
    "    )\n",
    "    bot.send_message(message.chat.id, welcome_text, reply_markup=markup)\n",
    "\n",
    "\n",
    "# === БЛОК СБОРА ПРЕДЛОЖКИ (МЕХАНИКА ЮЗЕРА) ===\n",
    "\n",
    "@bot.message_handler(commands=['add'])\n",
    "def start_add(message):\n",
    "    user_id = message.chat.id\n",
    "    # Создаем пустой черновик для этого пользователя\n",
    "    pending_submissions[user_id] = {}\n",
    "    \n",
    "    bot.send_message(user_id, \"📍 Шаг 1/2:\\nОтправь координаты кулера с Яндекс Карт.\\n(Зажми точку на карте, скопируй цифры и пришли сюда, например: `55.868368, 37.491889`)\")\n",
    "    # Перенаправляем следующий ответ пользователя в функцию сохранения координат\n",
    "    bot.register_next_step_handler(message, save_coordinates)\n",
    "\n",
    "def save_coordinates(message):\n",
    "    user_id = message.chat.id\n",
    "    \n",
    "    # Защита от дурака: если пользователь вместо координат написал другую команду\n",
    "    if message.text and message.text.startswith('/'):\n",
    "        bot.send_message(user_id, \"❌ Заполнение отменено. Вы ввели команду.\")\n",
    "        return\n",
    "\n",
    "    pending_submissions[user_id]['coords'] = message.text\n",
    "    bot.send_message(user_id, \"📸 Шаг 2/2:\\nТеперь отправь ФОТОГРАФИЮ этого кулера, чтобы подтвердить его наличие:\")\n",
    "    bot.register_next_step_handler(message, save_photo)\n",
    "\n",
    "def save_photo(message):\n",
    "    user_id = message.chat.id\n",
    "    \n",
    "    # Проверяем, прислал ли пользователь именно фото\n",
    "    if message.content_type != 'photo':\n",
    "        bot.send_message(user_id, \"⚠️ Это не фото! Пожалуйста, пришли именно фотографию кулера:\")\n",
    "        bot.register_next_step_handler(message, save_photo)\n",
    "        return\n",
    "\n",
    "    # Получаем id фотографии самого лучшего качества (последняя в списке)\n",
    "    photo_id = message.photo[-1].file_id\n",
    "    pending_submissions[user_id]['photo'] = photo_id\n",
    "    \n",
    "    # Сообщаем пользователю, что всё ок\n",
    "    bot.send_message(user_id, \"⏳ Спасибо! Твоя предложка отправлена администратору на проверку. Я пришлю уведомление о решении!\")\n",
    "    \n",
    "    # Создаем админ-кнопки под фоткой\n",
    "    keyboard = InlineKeyboardMarkup()\n",
    "    # В callback_data зашиваем действие и ID юзера, чтобы знать, кого модерировать\n",
    "    btn_approve = InlineKeyboardButton(\"✅ Одобрить\", callback_data=f\"approve_{user_id}\")\n",
    "    btn_reject = InlineKeyboardButton(\"❌ Отклонить\", callback_data=f\"reject_{user_id}\")\n",
    "    keyboard.add(btn_approve, btn_reject)\n",
    "    \n",
    "    # Формируем сообщение для тебя\n",
    "    admin_text = (\n",
    "        \"🚀 **НОВАЯ ПРЕДЛОЖКА ТОЧКИ!**\\n\\n\"\n",
    "        f\"От: @{message.from_user.username or 'Скрыт ник'}\\n\"\n",
    "        f\"Координаты: `{pending_submissions[user_id]['coords']}`\\n\\n\"\n",
    "        \"Проверь фото ниже и выбери действие:\"\n",
    "    )\n",
    "    \n",
    "    # Бот присылает фотку кулера и инфо тебе в личку\n",
    "    bot.send_photo(ADMIN_ID, photo_id, caption=admin_text, parse_mode=\"Markdown\", reply_markup=keyboard)\n",
    "\n",
    "\n",
    "# === БЛОК МОДЕРАЦИИ (МЕХАНИКА АДМИНА) ===\n",
    "\n",
    "@bot.callback_query_handler(func=lambda call: True)\n",
    "def handle_moderation(call):\n",
    "    # Разделяем команду и ID пользователя (например, \"approve_123456\" -> \"approve\", \"123456\")\n",
    "    action, target_user_id = call.data.split('_')\n",
    "    target_user_id = int(target_user_id)\n",
    "    \n",
    "    if action == \"approve\":\n",
    "        # 1. Пишем юзеру приятную новость\n",
    "        try:\n",
    "            bot.send_message(target_user_id, \"🎉 Ура! Твоя предложка была одобрена модератором. Спасибо за вклад в карту, скоро точка появится!\")\n",
    "        except Exception:\n",
    "            pass # На случай, если юзер заблокировал бота\n",
    "            \n",
    "        # 2. Меняем текст сообщения у тебя, чтобы убрать кнопки и зафиксировать статус\n",
    "        updated_caption = call.message.caption + \"\\n\\n🟢 **СТАТУС: ОДОБРЕНО**\\n(Не забудь внести координаты в index.html!)\"\n",
    "        bot.edit_message_caption(chat_id=ADMIN_ID, message_id=call.message.message_id, caption=updated_caption, reply_markup=None)\n",
    "        bot.answer_callback_query(call.id, \"Точка одобрена!\")\n",
    "        \n",
    "    elif action == \"reject\":\n",
    "        # 1. Спрашиваем у тебя причину удаления\n",
    "        msg = bot.send_message(ADMIN_ID, \"📝 Напиши в ответном сообщении причину отклонения (комментарий для пользователя):\")\n",
    "        # Передаем управление в функцию отправки отказа, прокидывая ID юзера и инфо о сообщении\n",
    "        bot.register_next_step_handler(msg, lambda message: send_rejection(message, target_user_id, call.message.message_id, call.message.caption))\n",
    "        bot.answer_callback_query(call.id)\n",
    "\n",
    "def send_rejection(message, target_user_id, orig_msg_id, orig_caption):\n",
    "    reason = message.text # Твой текст с причиной\n",
    "    \n",
    "    # 1. Отправляем пользователю отказ с твоим комментарием\n",
    "    try:\n",
    "        reject_text = f\"❌ К сожалению, твоя предложка кулера была отклонена модератором.\\n\\n💬 **Причина:** {reason}\"\n",
    "        bot.send_message(target_user_id, reject_text)\n",
    "    except Exception:\n",
    "        pass\n",
    "        \n",
    "    # 2. Обновляем статус сообщения в твоей админке\n",
    "    updated_caption = orig_caption + f\"\\n\\n🔴 **СТАТУС: ОТКЛОНЕНО**\\n💬 **Причина:** {reason}\"\n",
    "    bot.edit_message_caption(chat_id=ADMIN_ID, message_id=orig_msg_id, caption=updated_caption, reply_markup=None)\n",
    "    bot.send_message(ADMIN_ID, \"🔴 Отклонено. Пользователю отправлено уведомление.\")\n",
    "\n",
    "\n",
    "# Запуск бота\n",
    "print(\"Бот с админ-панелью успешно запущен!\")\n",
    "bot.remove_webhook()\n",
    "bot.polling(none_stop=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1+"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
